# -*- coding: utf-8 -*-
"""Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaosxqVUOalpAQy5s5k-fqC9IavW02TI

# **1. Load Data**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sales = pd.read_csv("/content/Superstore.csv", encoding="latin1")
print("First 5 rows:")
print(sales.head())

"""# **2. Inspect Data**"""

print("\nLast 5 rows:")
print(sales.tail())

print("\nData types:")
print(sales.dtypes)

print("\nMissing values:")
print(sales.isnull().sum())

print("\nSummary statistics:")
print(sales.describe())

print("\nShape:")
print(sales.shape)

print("\nColumns:")
print(sales.columns)

print("\nInfo:")
print(sales.info())

print("\nDuplicate Rows:")
print(sales.duplicated().sum())

"""# **3. Convert Data Type**"""

sales["Order Date"] = pd.to_datetime(sales["Order Date"])
sales["Ship Date"] = pd.to_datetime(sales["Ship Date"])

"""# **4. Modifying Columns & Filtering**"""

# Rounding
sales["Profit"] = sales["Profit"].round(2)
sales["Sales"] = sales["Sales"].round(2)

# Drop Columns
sales = sales.drop(columns = ["Row ID"])

# Sorting
sales = sales.sort_values(by = "Sales", ascending = False)
sales = sales.sort_values(by = "Profit", ascending = False)

# Filtering
profit = sales[sales["Profit"] > 0]
loss = sales[sales["Profit"] < 0]
print("profit:", profit["Profit"])
print("loss:", loss["Profit"])

# Handle Duplicates
sales = sales.drop_duplicates()

"""# **4. Sales Analysis**"""

# Total Sales
Total_sales = sales["Sales"].sum()
# Total Profit
Total_profit = sales["Profit"].sum()
# Total Quantity
Total_quantity = sales["Quantity"].sum()
# Average Sales
Average_Sales = sales["Sales"].mean()
# Count of order id
Count_order_id = sales["Order ID"].nunique()
# Total Discount
Total_Discount = sales["Discount"].sum()

print("\n===== SALES SUMMARY =====")
print("Total Sales:", Total_sales)
print("Total Profit:", Total_profit)
print("Total Quantity:", Total_quantity)
print("Average Sales:", Average_Sales)
print("Count of Order ID:", Count_order_id)
print("Total Discount:", Total_Discount)

"""# **5. Sales Statistics**"""

sales_values = sales["Sales"].values

np.mean(sales_values)
np.median(sales_values)
np.max(sales_values)
np.min(sales_values)
np.std(sales_values)

flags = np.where(sales_values > 100, "HIGH", "LOW")
print(flags)

"""# **6. Groupby**"""

# Sales by Category
sales_by_category = sales.groupby("Category")["Sales"].sum().sort_values(ascending=False)
print("\nSales by Category:")
print(sales_by_category)

# Profit by Category
profit_by_category = sales.groupby("Category")["Profit"].sum().sort_values(ascending=False)
print("\nProfit by Category:")
print(profit_by_category)

# Sales by Region
sales_by_region = sales.groupby("Region")["Sales"].sum().sort_values(ascending=False)
print("\nSales by Region:")
print(sales_by_region)

# Sales by Segment
sales_by_segment = sales.groupby("Segment")["Sales"].sum().sort_values(ascending=False)
print("\nSales by Segment:")
print(sales_by_segment)

# Sales by sub-category
sales_by_sub_category = sales.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False)
print("\nSales by Sub-Category:")
print(sales_by_sub_category)

# Top 10 States by Sales
top_10_states_by_sales = sales.groupby("State")["Sales"].sum().nlargest(10)
print("\nTop 10 States by Sales:")
print(top_10_states_by_sales)

# Sales Over Time
sales_over_time = sales.groupby("Order Date")["Sales"].sum()
print("\nSales Over Time:")
print(sales_over_time)

# count of order id by category
count_order_id = sales.groupby("Category")["Order ID"].count()
print("\nCount of Order ID by Category:")
print(count_order_id)

"""# **7. Sales by category Visualization**"""

plt.figure(figsize=(8, 5))

plt.bar(sales_by_category.index, sales_by_category.values)
plt.xlabel("Category")
plt.ylabel("Sales")
plt.title("Sales by Category")
plt.xticks(rotation=45)
plt.savefig("sales_by_category.png")
plt.show()

"""# **8. Profit By Category Visualization**"""

plt.figure(figsize=(8, 5))

plt.bar(profit_by_category.index, profit_by_category.values)
plt.xlabel("Category")
plt.ylabel("Profit")
plt.title("Profit by Category")
plt.savefig("profit_by_category.png")
plt.show()

"""# **9. Sales By Region Visualization**"""

plt.figure(figsize=(8, 5))

plt.bar(sales_by_region.index, sales_by_region.values)
plt.xlabel("Region")
plt.ylabel("Sales")
plt.title("Sales by Region")
plt.savefig("sales_by_region.png")
plt.show()

"""# **10. Sales Distribution**"""

plt.figure(figsize=(8, 5))

plt.hist(sales["Sales"], bins=20)
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.title("Sales Distribution")
plt.savefig("sales_distribution.png")
plt.show()

"""# **11. Quantity vs Sales**"""

plt.figure(figsize=(8, 5))

plt.scatter(sales["Quantity"], sales["Sales"])
plt.xlabel("Quantity")
plt.ylabel("Sales")
plt.title("Quantity vs Sales")
plt.savefig("quantity_vs_sales.png")
plt.show()

"""# **12. Sales over Time**"""

plt.figure(figsize=(8, 5))

plt.plot(sales_over_time.index, sales_over_time.values)
plt.xlabel("Order Date")
plt.ylabel("Sales")
plt.title("Sales Over Time")
plt.xticks(rotation=45)
plt.savefig("sales_over_time.png")
plt.show()

"""# **13. Top 10 States**"""

plt.figure(figsize=(8, 5))

plt.bar(top_10_states_by_sales.index, top_10_states_by_sales.values)
plt.xlabel("State")
plt.ylabel("Sales")
plt.title("Top 10 States by Sales")
plt.xticks(rotation=45)
plt.savefig("top_10_states_by_sales.png")
plt.show()

"""# **14. Validation**"""

print("\n===== FINAL VALIDATION =====")

print("\nMissing values: ")
print(sales.isnull().sum())

print("\nDuplicate rows: ")
print(sales.duplicated().sum().sum())

print("\nShape: ")
print(sales.shape)

print("\nData types: ")
print(sales.dtypes)